import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { createTradeEventRepository } from './repositories/trade-events.mjs';
import { createExecutionRequestRepository } from './repositories/execution-requests.mjs';
import { createCoreRepositories } from './repositories/core.mjs';
import { createAdminRepository } from './repositories/admin.mjs';
import { createMarketplaceRepository } from './repositories/marketplace.mjs';
import { createSignalIntelligenceRepository } from './repositories/signal-intelligence.mjs';
import { createWalletInfrastructureRepository } from './repositories/wallet-infrastructure.mjs';
import { runMigrations } from './migration-runner.mjs';
import { runShadowSimulation } from './shadow-simulator.mjs';
import { checkExecutionEngineRental } from './execution-rental-gate.mjs';
import { evaluateSignalQuality, getSignalQualityConfig } from './signal-intelligence.mjs';
import { createWalletAuthService } from './wallet-auth.mjs';
import { createAutomaticEvidenceService } from './automatic-evidence-service.mjs';
import { createReconciledPerformanceService } from './reconciled-performance-service.mjs';
import { createWalletPortfolioService } from './wallet-portfolio.mjs';
import { handleMemberAutoTradeRoute } from './member-autotrade-route.mjs';
import { evaluateAdminLiveControl } from './admin-live-control.mjs';
import { startMemberAutoTradeShadowScheduler } from './member-autotrade-shadow-scheduler.mjs';

const PORT = Number(process.env.PORT || 8080);
const executionMode = process.env.EXECUTION_MODE || 'SHADOW';
const liveEnabled = process.env.LIVE_ENABLED === 'true' && executionMode === 'LIVE';
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL }) : null;
const repos = pool ? { tradeEvents:createTradeEventRepository(pool), executionRequests:createExecutionRequestRepository(pool), ...createCoreRepositories(pool), admin:createAdminRepository(pool), marketplace:createMarketplaceRepository(pool), signalIntelligence:createSignalIntelligenceRepository(pool), walletInfrastructure:createWalletInfrastructureRepository(pool) } : null;
const walletAuth = pool ? createWalletAuthService(pool) : null;
const automaticEvidence = pool ? createAutomaticEvidenceService(pool,{rpcUrl:process.env.SOLANA_RPC_URL,endpointLabel:process.env.SOLANA_RPC_ENDPOINT_LABEL||'solana-rpc'}) : null;
const reconciledPerformance = pool ? createReconciledPerformanceService(pool) : null;
const walletPortfolio = createWalletPortfolioService({rpcUrl:process.env.SOLANA_RPC_URL});
const VERSION = '2026.09.04-member-autotrade-shadow';
let memberShadowScheduler = { enabled:false, reason:'not_started', stop() {}, status(){ return {enabled:false,reason:this.reason,mode:'SHADOW',live_execution_authorized:false}; } };
const schedulerSnapshot=()=>typeof memberShadowScheduler?.status==='function'?memberShadowScheduler.status():{enabled:memberShadowScheduler?.enabled===true,mode:'SHADOW',live_execution_authorized:false};
const send=(res,status,body,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type.startsWith('text/')?body:JSON.stringify(body));};
const auth=req=>Boolean(process.env.API_TOKEN)&&req.headers.authorization===`Bearer ${process.env.API_TOKEN}`;
const adminAuth=req=>Boolean(process.env.ADMIN_API_TOKEN)&&req.headers.authorization===`Bearer ${process.env.ADMIN_API_TOKEN}`;
const bearerToken=req=>{const value=String(req.headers.authorization||'');return value.startsWith('Bearer ')?value.slice(7).trim():'';};
const jsonBody=async req=>{let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw,'utf8')>32768)throw new Error('request_body_too_large');}return raw?JSON.parse(raw):{};};
const requestUrl=req=>new URL(req.url||'/','http://localhost');
const pathname=req=>requestUrl(req).pathname.replace(/\/+$/,'')||'/';
const parts=req=>pathname(req).split('/').filter(Boolean);
const rentalProjection=r=>r?({rental_id:r.rental_id,trader_id:r.trader_id,status:r.status,monthly_rate_bps:r.monthly_rate_bps,amount_due_usd:r.amount_due_usd,currency:r.currency,period_start:r.period_start,period_end:r.period_end,paid_at:r.paid_at,payment_status:r.payment_status,payment_reference:r.payment_reference,created_at:r.created_at,updated_at:r.updated_at}):null;
const assessmentProjection=r=>r?({source_type:r.source_type,token_mint:r.token_mint,quote_mint:r.quote_mint,quality_score:Number(r.quality_score),verdict:r.verdict,hard_rejects:r.hard_rejects||[],components:r.components||{},snapshot:r.snapshot||{},observed_at:r.observed_at,live_execution_authorized:false,quality_first:true}):null;
const sessionFor=async req=>{if(!walletAuth)return null;const token=bearerToken(req);if(!token)return null;return walletAuth.getSession(token);};
const errorStatus=e=>{const code=String(e?.message||'');if(code==='request_body_too_large')return 413;if(code==='auth_rate_limited')return 429;if(code==='solana_rpc_unconfigured')return 503;if(['solana_rpc_http_error','solana_rpc_error','solana_rpc_timeout'].includes(code))return 502;if(['auth_challenge_used','trader_application_exists','copy_mandate_exists','copy_mandate_cancelled','trader_verification_invalid_state','trader_evidence_invalid_state','trader_publication_gate_failed','reconciliation_conflict'].includes(code))return 409;if(['required_consents_missing','account_not_active','trader_not_copyable','trader_not_shadow','self_copy_not_allowed','synthetic_trade_event_blocked'].includes(code))return 403;if(['trader_application_not_found','copy_mandate_not_found','trader_evidence_not_found','trade_event_not_found'].includes(code))return 404;if(['auth_challenge_not_found','auth_challenge_expired','invalid_wallet_signature','wallet_mismatch','session_invalid'].includes(code))return 401;if(code.startsWith('invalid_')||code.startsWith('reconciliation_')||code.endsWith('_required')||code==='signature_required'||code==='trader_review_invalid_state')return 400;return 500;};

const server=http.createServer(async(req,res)=>{try{
 const route=pathname(req),p=parts(req);
 if(await handleMemberAutoTradeRoute({req,res,route,pool,repos,walletAuth,sessionFor,jsonBody,send,executionMode,liveEnabled,walletPortfolio,assessmentProjection}))return;
 if(req.method==='GET'&&route==='/api/health')return send(res,200,{status:'ok',service:'aether-api',execution_mode:executionMode,live_enabled:liveEnabled,auth_mode:'WALLET_SIGNATURE',version:VERSION});
 if(req.method==='GET'&&route==='/api/readiness'){if(!pool)return send(res,503,{status:'not_ready',database:'unconfigured',version:VERSION});try{await pool.query('SELECT 1');return send(res,200,{status:'ready',database:'ok',version:VERSION});}catch{return send(res,503,{status:'not_ready',database:'unavailable',version:VERSION});}}
 if(req.method==='GET'&&route==='/api/version')return send(res,200,{version:VERSION,execution_mode:executionMode,live_enabled:liveEnabled});
 if(req.method==='GET'&&route==='/api/execution/status')return send(res,200,{mode:executionMode,live_enabled:liveEnabled,fail_closed:!liveEnabled,signer_exposed_to_api:false});
 if(req.method==='GET'&&route==='/api/signals/config')return send(res,200,{source_type:'MACHINE_INTELLIGENCE',quality_first:true,live_execution_authorized:false,config:getSignalQualityConfig()});
 if(req.method==='GET'&&route==='/api/autotrade/status')return send(res,200,{source_type:'ALGORITHMIC_STRATEGY',mode:'SHADOW',quality_first:true,live_execution_authorized:false,execution_dispatched:false,fail_closed:true});
 if(req.method==='POST'&&route==='/api/auth/challenge'){if(!walletAuth)return send(res,503,{error:'database_unconfigured'});const body=await jsonBody(req);const challenge=await walletAuth.issueChallenge({walletAddress:body.wallet_address,purpose:body.purpose||'LOGIN'});return send(res,201,{challenge});}
 if(req.method==='POST'&&route==='/api/auth/verify'){if(!walletAuth)return send(res,503,{error:'database_unconfigured'});const body=await jsonBody(req);const result=await walletAuth.verifyLogin({challengeId:body.challenge_id,walletAddress:body.wallet_address,signature:body.signature,signatureEncoding:body.signature_encoding||'base64',consents:body.consents||[]});return send(res,200,result);}
 if(req.method==='GET'&&route==='/api/auth/session'){if(!walletAuth)return send(res,503,{error:'database_unconfigured'});const token=bearerToken(req);if(!token)return send(res,401,{error:'session_required'});const session=await walletAuth.getSession(token);if(!session)return send(res,401,{error:'session_invalid'});return send(res,200,{authenticated:true,user:{user_id:session.user_id,username:session.username,display_name:session.display_name,status:session.status,primary_wallet:session.primary_wallet},session:{session_id:session.session_id,expires_at:session.expires_at}});}
 if(req.method==='POST'&&route==='/api/auth/logout'){if(!walletAuth)return send(res,503,{error:'database_unconfigured'});const token=bearerToken(req);if(!token)return send(res,401,{error:'session_required'});const revoked=await walletAuth.revokeSession(token);if(!revoked)return send(res,401,{error:'session_invalid'});return send(res,200,{revoked:true});}

 if(req.method==='GET'&&route==='/api/account/wallet-portfolio'){
   if(!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   return send(res,200,await walletPortfolio.getPortfolio(session.primary_wallet));
 }
 if(req.method==='GET'&&route==='/api/account/trader'){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const trader=await repos.marketplace.getOwnedTrader(session.user_id);
   return send(res,200,{trader,mode:'SHADOW',live_execution_authorized:false,publication_requires_verification:true});
 }
 if(req.method==='POST'&&route==='/api/account/trader/challenge'){
   if(!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const challenge=await walletAuth.issueChallenge({walletAddress:session.primary_wallet,purpose:'BECOME_TRADER'});
   return send(res,201,{challenge,live_execution_authorized:false});
 }
 if(req.method==='POST'&&route==='/api/account/trader/apply'){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const body=await jsonBody(req);
   if(body.wallet_address!==session.primary_wallet)return send(res,401,{error:'wallet_mismatch'});
   const proof=await walletAuth.verifyOwnership({challengeId:body.challenge_id,walletAddress:body.wallet_address,purpose:'BECOME_TRADER',signature:body.signature,signatureEncoding:body.signature_encoding||'base64'});
   const trader=await repos.marketplace.createTraderApplication({userId:session.user_id,walletAddress:session.primary_wallet,displayName:body.display_name,bio:body.bio||'',strategySummary:body.strategy_summary||''});
   await repos.auditEvents.append({event_type:'TRADER_APPLICATION_SUBMITTED',actor:session.primary_wallet,entity_type:'trader',entity_id:String(trader.trader_id),payload:{user_id:session.user_id,wallet_address:session.primary_wallet,ownership_verified:proof.verified,onboarding_status:trader.onboarding_status,verification_status:trader.verification_status,published:false,mode:'SHADOW',live_execution_authorized:false}});
   return send(res,201,{trader,ownership_proof:{verified:true,purpose:'BECOME_TRADER',transaction_authorized:false,funds_authorized:false},live_execution_authorized:false});
 }

 if(req.method==='GET'&&route==='/api/account/copy-mandates'){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   return send(res,200,{items:await repos.copyPolicies.listForFollower(session.user_id),mode:'SHADOW',live_execution_authorized:false});
 }
 if(req.method==='GET'&&route==='/api/account/copy-trades'){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const items=await repos.executionRequests.listForFollower(session.user_id,requestUrl(req).searchParams.get('limit'));
   const inFlight=items.filter(item=>['PENDING','QUEUED'].includes(item.status)).length;
   const simulated=items.filter(item=>item.status==='SIMULATED').length;
   const completed=items.filter(item=>item.status==='EXECUTED').length;
   const failed=items.filter(item=>['REJECTED','FAILED'].includes(item.status)).length;
   return send(res,200,{items,summary:{in_flight:inFlight,simulated,completed,failed},open_positions:[],position_accounting_ready:false,mode:'SHADOW',live_execution_authorized:false});
 }
 if(req.method==='POST'&&route==='/api/account/copy-mandates'){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const mandate=await repos.copyPolicies.createForFollower(session.user_id,await jsonBody(req));
   await repos.auditEvents.append({event_type:'COPY_MANDATE_CREATED',actor:session.primary_wallet,entity_type:'copy_policy',entity_id:String(mandate.policy_id),payload:{trader_id:mandate.trader_id,mode:'SHADOW',allocation_bps:mandate.allocation_bps,max_copy_amount_usd:mandate.max_copy_amount_usd,max_position_amount_usd:mandate.max_position_amount_usd,max_slippage_bps:mandate.max_slippage_bps,max_daily_loss_bps:mandate.max_daily_loss_bps,stop_drawdown_bps:mandate.stop_drawdown_bps,policy_type:mandate.policy_type,policy_value:mandate.policy_value,consent_version:mandate.consent_version,consented_at:mandate.consented_at,live_execution_authorized:false}});
   return send(res,201,{mandate,mode:'SHADOW',live_execution_authorized:false});
 }
 if(req.method==='PATCH'&&p[1]==='account'&&p[2]==='copy-mandates'&&p[3]){
   if(!repos||!walletAuth)return send(res,503,{error:'database_unconfigured'});
   const session=await sessionFor(req);if(!session)return send(res,401,{error:'session_required'});
   const body=await jsonBody(req);const mandate=await repos.copyPolicies.updateForFollower(session.user_id,p[3],body);
   await repos.auditEvents.append({event_type:'COPY_MANDATE_UPDATED',actor:session.primary_wallet,entity_type:'copy_policy',entity_id:String(mandate.policy_id),payload:{action:String(body.action||'UPDATE').toUpperCase(),status:mandate.status,enabled:mandate.enabled,mode:'SHADOW',live_execution_authorized:false}});
   return send(res,200,{mandate,mode:'SHADOW',live_execution_authorized:false});
 }

 if(req.method==='POST'&&route==='/api/signals/evaluate'){if(!auth(req))return send(res,401,{error:'unauthorized'});if(!repos)return send(res,503,{error:'database_unconfigured'});const assessment=evaluateSignalQuality(await jsonBody(req));const stored=await repos.signalIntelligence.recordAssessment(assessment);await repos.auditEvents.append({event_type:'MACHINE_SIGNAL_ASSESSED',actor:'signal-intelligence',entity_type:'signal_assessment',entity_id:String(stored.assessment_id),payload:{token_mint:assessment.token_mint,quality_score:assessment.quality_score,verdict:assessment.verdict,hard_rejects:assessment.hard_rejects,live_execution_authorized:false}});return send(res,200,{assessment_id:stored.assessment_id,assessment});}
 if(req.method==='GET'&&route==='/api/signals/recent'){if(!auth(req))return send(res,401,{error:'unauthorized'});if(!repos)return send(res,503,{error:'database_unconfigured'});return send(res,200,{items:await repos.signalIntelligence.recentAssessments(requestUrl(req).searchParams.get('limit'))});}
 if(req.method==='GET'&&route==='/api/autotrade/decisions'){if(!auth(req))return send(res,401,{error:'unauthorized'});if(!repos)return send(res,503,{error:'database_unconfigured'});return send(res,200,{items:await repos.signalIntelligence.recentDecisions(requestUrl(req).searchParams.get('limit'))});}
 if(req.method==='POST'&&route==='/api/shadow/simulate'){if(!auth(req))return send(res,401,{error:'unauthorized'});if(!repos)return send(res,503,{error:'database_unconfigured'});if(liveEnabled||executionMode!=='SHADOW')return send(res,409,{error:'shadow_simulation_locked',reason:'execution_mode_not_shadow'});const result=await runShadowSimulation({repos,pool,body:await jsonBody(req)});return send(res,result.status,result.body);}
 if(req.method==='GET'&&p[1]==='trades')return send(res,200,{items:await repos.tradeEvents.recent(requestUrl(req).searchParams.get('limit'))});
 if(req.method==='GET'&&p[1]==='traders'){if(p[2]){const t=await repos.marketplace.getTrader(p[2]);return t?send(res,200,t):send(res,404,{error:'trader_not_found'});}return send(res,200,{items:await repos.marketplace.listTraders(requestUrl(req).searchParams.get('limit'))});}
 if(req.method==='GET'&&route==='/api/marketplace/fees')return send(res,200,{config:await repos.marketplace.getFeeConfig()});
 if(req.method==='GET'&&route==='/api/execution/rental/status'){if(!auth(req))return send(res,401,{error:'unauthorized'});const traderId=requestUrl(req).searchParams.get('trader_id');if(!traderId)return send(res,400,{error:'trader_id_required'});return send(res,200,await checkExecutionEngineRental(pool,traderId));}
 if(req.method==='POST'&&route==='/api/execution/rental'){if(!auth(req))return send(res,401,{error:'unauthorized'});const body=await jsonBody(req);if(!body.trader_id)return send(res,400,{error:'trader_id_required'});const trader=await repos.marketplace.getTrader(body.trader_id);if(!trader)return send(res,404,{error:'trader_not_found'});const start=new Date(body.period_start||Date.now()),end=body.period_end?new Date(body.period_end):new Date(start.getTime()+30*24*60*60*1000);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)return send(res,400,{error:'invalid_rental_period'});const feeConfig=await repos.marketplace.getFeeConfig(),rate=Number(body.monthly_rate_bps??feeConfig?.execution_rental_fee_bps??300),amount=Number(body.amount_due_usd??0);if(!Number.isInteger(rate)||rate<0||rate>10000)return send(res,400,{error:'invalid_rental_rate'});if(!Number.isFinite(amount)||amount<0)return send(res,400,{error:'invalid_rental_amount'});const paid=body.payment_status==='PAID'||Boolean(body.paid_at);const q=await pool.query(`INSERT INTO execution_engine_rentals (trader_id,status,monthly_rate_bps,amount_due_usd,period_start,period_end,paid_at,payment_status,payment_reference) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[body.trader_id,paid?'ACTIVE':'PAST_DUE',rate,amount,start,end,body.paid_at?new Date(body.paid_at):null,paid?'PAID':'PENDING',body.payment_reference||null]);const rental=q.rows[0];await pool.query(`INSERT INTO billing_ledger(trader_id,rental_id,fee_type,amount_usd,currency,status,period_start,period_end,reference_id) VALUES($1,$2,'EXECUTION_ENGINE_RENTAL',$3,$4,$5,$6,$7,$8)`,[rental.trader_id,rental.rental_id,rental.amount_due_usd,rental.currency,paid?'PAID':'PENDING',rental.period_start,rental.period_end,rental.payment_reference||String(rental.rental_id)]);return send(res,201,{rental:rentalProjection(rental)});}
 if(req.method==='PATCH'&&route==='/api/execution/rental/payment'){if(!auth(req))return send(res,401,{error:'unauthorized'});const body=await jsonBody(req);if(!body.rental_id)return send(res,400,{error:'rental_id_required'});if(!['PAID','FAILED','REFUNDED','VOID','PENDING'].includes(body.payment_status))return send(res,400,{error:'invalid_payment_status'});const paid=body.payment_status==='PAID';const q=await pool.query(`UPDATE execution_engine_rentals SET payment_status=$1,payment_reference=COALESCE($2,payment_reference),paid_at=CASE WHEN $3 THEN COALESCE(paid_at,now()) ELSE paid_at END,status=CASE WHEN $3 AND period_end>now() THEN 'ACTIVE' WHEN $4='PAID' AND period_end<=now() THEN 'EXPIRED' ELSE status END,updated_at=now() WHERE rental_id=$5 RETURNING *`,[body.payment_status,body.payment_reference||null,paid,body.payment_status,body.rental_id]);if(!q.rows[0])return send(res,404,{error:'rental_not_found'});const rental=q.rows[0];await pool.query(`UPDATE billing_ledger SET status=$1,reference_id=COALESCE($2,reference_id) WHERE rental_id=$3 AND fee_type='EXECUTION_ENGINE_RENTAL' AND status<>'VOID'`,[paid?'PAID':body.payment_status,body.payment_reference||null,rental.rental_id]);return send(res,200,{rental:rentalProjection(rental)});}
 if(req.method==='GET'&&route==='/api/execution/rentals'){if(!auth(req))return send(res,401,{error:'unauthorized'});const traderId=requestUrl(req).searchParams.get('trader_id'),q=await pool.query(`SELECT rental_id,trader_id,status,monthly_rate_bps,amount_due_usd,currency,period_start,period_end,paid_at,payment_status,payment_reference,created_at,updated_at FROM execution_engine_rentals ${traderId?'WHERE trader_id=$1':''} ORDER BY created_at DESC LIMIT 200`,traderId?[traderId]:[]);return send(res,200,{items:q.rows.map(rentalProjection)});}
 if(req.method==='POST'&&route==='/api/executions'){if(!auth(req))return send(res,401,{error:'unauthorized'});const body=await jsonBody(req),mode=body.mode||'SHADOW';if(mode==='LIVE')return send(res,423,{error:'live_execution_blocked'});const access=await checkExecutionEngineRental(pool,body.trader_id);if(!access.allowed)return send(res,403,{error:'execution_engine_rental_required',reason:access.reason,rental:access.rental??null});return send(res,201,await repos.executionRequests.create({...body,mode}));}
 if(req.method==='GET'&&route==='/api/executions'){if(!auth(req))return send(res,401,{error:'unauthorized'});return send(res,200,{items:(await pool.query('SELECT * FROM execution_requests ORDER BY created_at DESC LIMIT 200')).rows});}

 if(req.method==='POST'&&p[1]==='internal'&&p[2]==='traders'&&p[3]&&p[4]==='reconciled-trades'){
   if(!auth(req))return send(res,401,{error:'unauthorized'});
   if(!reconciledPerformance||!repos)return send(res,503,{error:'database_unconfigured'});
   if(liveEnabled||executionMode!=='SHADOW')return send(res,423,{error:'reconciliation_shadow_only'});
   const rows=await reconciledPerformance.recordTrades(p[3],await jsonBody(req));
   await repos.auditEvents.append({event_type:'TRADER_RECONCILED_TRADES_RECORDED',actor:'reconciliation-service',entity_type:'trader',entity_id:String(p[3]),payload:{count:rows.length,trade_event_ids:rows.map(r=>r.trade_event_id),source_hashes:rows.map(r=>r.source_hash),mode:'SHADOW',verified:false,published:false,live_execution_authorized:false}});
   return send(res,201,{items:rows,mode:'SHADOW',verification_authorized:false,publication_authorized:false,live_execution_authorized:false});
 }
 if(req.method==='GET'&&p[1]==='internal'&&p[2]==='traders'&&p[3]&&p[4]==='reconciled-trades'){
   if(!auth(req))return send(res,401,{error:'unauthorized'});
   if(!reconciledPerformance)return send(res,503,{error:'database_unconfigured'});
   return send(res,200,{items:await reconciledPerformance.listTrades(p[3],requestUrl(req).searchParams.get('limit')),mode:'SHADOW',live_execution_authorized:false});
 }

 if(route.startsWith('/api/admin/')){if(!adminAuth(req))return send(res,401,{error:'admin_unauthorized'});if(!repos)return send(res,503,{error:'database_unconfigured'});}
 if(req.method==='GET'&&route==='/api/admin/runtime'){const counts=(await pool.query(`SELECT state,count(*)::int AS count FROM member_autotrade_states GROUP BY state ORDER BY state`)).rows;return send(res,200,{execution_mode:executionMode,live_enabled:liveEnabled,member_autotrade_scheduler:schedulerSnapshot(),member_state_counts:counts,min_expected_net_edge_bps:20,strategy:'TWO_LEG_ARBITRAGE',dex_pair:'ORCA_RAYDIUM',mode:'SHADOW',live_execution_authorized:false});}
 if(req.method==='POST'&&route==='/api/admin/runtime/scheduler'){if(executionMode!=='SHADOW'||liveEnabled)return send(res,423,{error:'shadow_scheduler_live_blocked',live_execution_authorized:false});const body=await jsonBody(req);if(typeof body.enabled!=='boolean')throw new Error('invalid_shadow_scheduler_enabled');if(body.enabled){if(schedulerSnapshot().enabled!==true)memberShadowScheduler=startMemberAutoTradeShadowScheduler({pool,repos,env:{...process.env,AUTOTRADE_SHADOW_SCHEDULER_ENABLED:'true',EXECUTION_MODE:'SHADOW',LIVE_ENABLED:'false'}});}else{try{memberShadowScheduler.stop()}catch{}memberShadowScheduler={enabled:false,reason:'admin_stopped',stop(){},status(){return {enabled:false,reason:'admin_stopped',mode:'SHADOW',live_execution_authorized:false}}};}const snapshot=schedulerSnapshot();await repos.auditEvents.append({event_type:'ADMIN_SHADOW_AUTOTRADE_SCHEDULER_UPDATED',actor:'admin',entity_type:'runtime_control',entity_id:'member-autotrade-shadow-scheduler',payload:{enabled:snapshot.enabled===true,mode:'SHADOW',live_execution_authorized:false}});return send(res,200,{scheduler:snapshot,mode:'SHADOW',live_execution_authorized:false});}
 if(req.method==='GET'&&route==='/api/admin/live-control')return send(res,200,{...evaluateAdminLiveControl({action:'STATUS',adminAuthenticated:true,env:process.env}),runtime_mutation_applied:false,mode:'SHADOW'});
 if(req.method==='POST'&&route==='/api/admin/live-control'){const body=await jsonBody(req);const result=evaluateAdminLiveControl({action:body.action||'STATUS',adminAuthenticated:true,env:process.env});await repos.auditEvents.append({event_type:'ADMIN_LIVE_CONTROL_EVALUATED',actor:'admin',entity_type:'runtime_control',entity_id:String(body.action||'STATUS').toUpperCase(),payload:{action:result.action,accepted:result.accepted,effective_mode:result.effective_mode,fail_closed:true,runtime_mutation_applied:false,live_execution_authorized:result.gate?.live_execution_authorized===true}});return send(res,result.accepted?200:409,{...result,runtime_mutation_applied:false,mode:'SHADOW'});}
 if(req.method==='GET'&&route==='/api/admin/subscriptions'){const [prices,summary,orders]=await Promise.all([pool.query(`SELECT price_id,duration_days,base_price_usdc_atomic::text,discount_bps,final_price_usdc_atomic::text,promo_enabled,promo_start,promo_end,active,price_version,created_by,created_at FROM subscription_price_versions ORDER BY duration_days,price_version DESC`),pool.query(`SELECT (SELECT count(*) FROM user_accounts) AS members_total,(SELECT count(*) FROM member_subscriptions WHERE status='ACTIVE' AND service_expires_at>now()) AS subscriptions_active,(SELECT count(*) FROM subscription_orders WHERE status='PENDING_PAYMENT' AND quote_expires_at>now()) AS pending_orders,(SELECT count(*) FROM subscription_payments) AS verified_payments`),pool.query(`SELECT order_id,user_id,member_wallet,duration_days,final_price_usdc_atomic::text,status,quoted_at,quote_expires_at,created_at FROM subscription_orders ORDER BY created_at DESC LIMIT 50`)]);return send(res,200,{catalog:prices.rows,summary:summary.rows[0],recent_orders:orders.rows,pricing_authority:'SERVER_VERSIONED',payment_verification:'SOLANA_FINALIZED_RPC',live_execution_authorized:false});}
 if(req.method==='POST'&&route==='/api/admin/subscriptions/prices'){const body=await jsonBody(req);const duration=Number(body.duration_days),base=BigInt(String(body.base_price_usdc_atomic||'0')),discount=Number(body.discount_bps||0),active=body.active===true,promo=body.promo_enabled===true;if(![30,90,180,360].includes(duration))throw new Error('invalid_subscription_duration');if(base<=0n)throw new Error('invalid_subscription_base_price');if(!Number.isInteger(discount)||discount<0||discount>10000)throw new Error('invalid_subscription_discount_bps');const final=(base*BigInt(10000-discount))/10000n;if(final<=0n)throw new Error('invalid_subscription_final_price');const client=await pool.connect();try{await client.query('BEGIN');const version=Number((await client.query('SELECT COALESCE(MAX(price_version),0)+1 AS v FROM subscription_price_versions WHERE duration_days=$1',[duration])).rows[0].v);if(active)await client.query('UPDATE subscription_price_versions SET active=false WHERE duration_days=$1',[duration]);const priceId=`price-${duration}-v${version}-${randomUUID()}`;const row=(await client.query(`INSERT INTO subscription_price_versions(price_id,duration_days,base_price_usdc_atomic,discount_bps,final_price_usdc_atomic,promo_enabled,promo_start,promo_end,active,price_version,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING price_id,duration_days,base_price_usdc_atomic::text,discount_bps,final_price_usdc_atomic::text,promo_enabled,promo_start,promo_end,active,price_version,created_by,created_at`,[priceId,duration,base.toString(),discount,final.toString(),promo,body.promo_start||null,body.promo_end||null,active,version,'admin-control-panel'])).rows[0];await client.query('COMMIT');await repos.auditEvents.append({event_type:'SUBSCRIPTION_PRICE_VERSION_CREATED',actor:'admin',entity_type:'subscription_price',entity_id:priceId,payload:{duration_days:duration,base_price_usdc_atomic:base.toString(),discount_bps:discount,final_price_usdc_atomic:final.toString(),active,price_version:version,mode:'SHADOW',live_execution_authorized:false}});return send(res,201,{price:row,mode:'SHADOW',live_execution_authorized:false});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 if(req.method==='GET'&&route==='/api/admin/members'){const rows=await pool.query(`SELECT ua.user_id::text,ua.username,ua.display_name,ua.status,ua.created_at,uw.wallet_address,ms.status AS subscription_status,ms.service_expires_at,mda.status AS authority_status,mda.expires_at AS authority_expires_at,mas.state AS autotrade_state,mas.updated_at AS autotrade_updated_at FROM user_accounts ua LEFT JOIN LATERAL (SELECT wallet_address FROM user_wallets WHERE user_id=ua.user_id AND is_primary=true LIMIT 1) uw ON true LEFT JOIN LATERAL (SELECT status,service_expires_at FROM member_subscriptions WHERE user_id=ua.user_id::text ORDER BY service_expires_at DESC LIMIT 1) ms ON true LEFT JOIN LATERAL (SELECT status,expires_at FROM member_delegated_authorities WHERE user_id=ua.user_id::text ORDER BY created_at DESC LIMIT 1) mda ON true LEFT JOIN member_autotrade_states mas ON mas.user_id=ua.user_id::text ORDER BY ua.created_at DESC LIMIT 200`);return send(res,200,{items:rows.rows,mode:'SHADOW',live_execution_authorized:false});}
 if(req.method==='PATCH'&&p[1]==='admin'&&p[2]==='members'&&p[3]&&p[4]==='status'){const body=await jsonBody(req);const status=String(body.status||'').toUpperCase();if(!['ACTIVE','SUSPENDED','CLOSED'].includes(status))throw new Error('invalid_member_status');const member=(await pool.query('UPDATE user_accounts SET status=$1,updated_at=now() WHERE user_id=$2::uuid RETURNING user_id::text,username,display_name,status,updated_at',[status,p[3]])).rows[0];if(!member)return send(res,404,{error:'member_not_found'});await repos.auditEvents.append({event_type:'ADMIN_MEMBER_STATUS_UPDATED',actor:'admin',entity_type:'member',entity_id:member.user_id,payload:{status,mode:'SHADOW',live_execution_authorized:false}});return send(res,200,{member,mode:'SHADOW',live_execution_authorized:false});}
 if(req.method==='GET'&&route==='/api/admin/wallets'){const [items,readiness]=await Promise.all([repos.walletInfrastructure.list(),repos.walletInfrastructure.readiness()]);return send(res,200,{items,readiness});}
 if(req.method==='GET'&&route==='/api/admin/wallets/readiness')return send(res,200,await repos.walletInfrastructure.readiness());
 if(req.method==='PUT'&&p[1]==='admin'&&p[2]==='wallets'&&p[3]){const wallet=await repos.walletInfrastructure.upsert(p[3],await jsonBody(req));await repos.auditEvents.append({event_type:'PLATFORM_WALLET_CONFIG_UPDATED',actor:'admin',entity_type:'platform_wallet',entity_id:wallet.role,payload:{role:wallet.role,network:wallet.network,public_address:wallet.public_address,custody_model:wallet.custody_model,enabled:wallet.enabled,verification_status:wallet.verification_status,private_key_stored:false}});return send(res,200,{wallet,readiness:await repos.walletInfrastructure.readiness()});}
 if(req.method==='GET'&&route==='/api/admin/risk')return send(res,200,{items:await repos.admin.recentRiskDecisions()});
 if(req.method==='GET'&&route==='/api/admin/audit')return send(res,200,{items:await repos.admin.recentAuditEvents()});
 if(req.method==='GET'&&route==='/api/admin/traders/applications')return send(res,200,{items:await repos.marketplace.listTraderApplications(requestUrl(req).searchParams.get('limit'))});
 if(req.method==='PATCH'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='review'){const body=await jsonBody(req);const trader=await repos.marketplace.reviewTraderApplication(p[3],body);await repos.auditEvents.append({event_type:'TRADER_APPLICATION_REVIEWED',actor:'admin',entity_type:'trader',entity_id:String(trader.trader_id),payload:{decision:String(body.decision||'').toUpperCase(),onboarding_status:trader.onboarding_status,verification_status:trader.verification_status,published:trader.published,live_execution_authorized:false}});return send(res,200,{trader,publication_authorized:false,reason:'verifiable_data_required'});}
 if(req.method==='GET'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='evidence'&&p[5]==='collections')return send(res,200,{items:await automaticEvidence.listCollections(p[3],requestUrl(req).searchParams.get('limit')),mode:'SHADOW',live_execution_authorized:false});
 if(req.method==='POST'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='evidence'&&p[5]==='collect'){
   if(!automaticEvidence)return send(res,503,{error:'database_unconfigured'});
   const collection=await automaticEvidence.collectSolana(p[3],await jsonBody(req));
   await repos.auditEvents.append({event_type:'TRADER_SOLANA_EVIDENCE_COLLECTED',actor:'admin',entity_type:'trader_evidence_collection',entity_id:String(collection.collection_id),payload:{trader_id:collection.trader_id,source_type:collection.source_type,source_reference:collection.source_reference,collection_status:collection.collection_status,reason:collection.reason,source_hash:collection.provenance?.source_hash||null,metrics_available:false,verified:false,published:false,live_execution_authorized:false}});
   return send(res,201,{collection,evidence_recorded:false,verification_authorized:false,publication_authorized:false,live_execution_authorized:false});
 }
 if(req.method==='POST'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='evidence'&&p[5]==='reconcile'){
   if(!reconciledPerformance)return send(res,503,{error:'database_unconfigured'});
   if(liveEnabled||executionMode!=='SHADOW')return send(res,423,{error:'reconciliation_shadow_only'});
   const result=await reconciledPerformance.buildPerformanceEvidence(p[3]);
   await repos.auditEvents.append({event_type:'TRADER_RECONCILED_PERFORMANCE_EVIDENCE_BUILT',actor:'admin',entity_type:'trader_evidence_collection',entity_id:String(result.collection?.collection_id||''),payload:{trader_id:p[3],collection_status:result.collection?.collection_status,source_reference:result.collection?.source_reference,metrics_available:result.collection?.metrics_available===true,trades_count:result.collection?.trades_count,reputation_score:result.collection?.reputation_score,evidence_id:result.evidence?.evidence_id||null,reused:result.reused===true,verified:false,published:false,live_execution_authorized:false}});
   return send(res,result.reused?200:201,{...result,evidence_recorded:Boolean(result.evidence),verification_authorized:false,publication_authorized:false,live_execution_authorized:false});
 }
 if(req.method==='GET'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='evidence'&&!p[5])return send(res,200,{items:await repos.marketplace.listTraderVerificationEvidence(p[3],requestUrl(req).searchParams.get('limit'))});
 if(req.method==='POST'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='evidence'&&!p[5]){const evidence=await repos.marketplace.recordTraderVerificationEvidence(p[3],await jsonBody(req));await repos.auditEvents.append({event_type:'TRADER_VERIFICATION_EVIDENCE_RECORDED',actor:'admin',entity_type:'trader_verification_evidence',entity_id:String(evidence.evidence_id),payload:{trader_id:evidence.trader_id,source_type:evidence.source_type,source_reference:evidence.source_reference,observed_at:evidence.observed_at,evidence_status:evidence.evidence_status,live_execution_authorized:false}});return send(res,201,{evidence,publication_authorized:false});}
 if(req.method==='PATCH'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='verification'){const body=await jsonBody(req);const trader=await repos.marketplace.reviewTraderVerification(p[3],body);await repos.auditEvents.append({event_type:'TRADER_DATA_VERIFICATION_REVIEWED',actor:'admin',entity_type:'trader',entity_id:String(trader.trader_id),payload:{decision:String(body.decision||'').toUpperCase(),evidence_id:body.evidence_id,verification_status:trader.verification_status,verified:trader.verified,published:trader.published,verification_source:trader.verification_source,live_execution_authorized:false}});return send(res,200,{trader,publication_authorized:false,publication_requires_explicit_action:true});}
 if(req.method==='PATCH'&&p[1]==='admin'&&p[2]==='traders'&&p[3]&&p[4]==='publication'){const body=await jsonBody(req);const trader=await repos.marketplace.setTraderPublished(p[3],body);await repos.auditEvents.append({event_type:trader.published?'TRADER_MARKETPLACE_PUBLISHED':'TRADER_MARKETPLACE_UNPUBLISHED',actor:'admin',entity_type:'trader',entity_id:String(trader.trader_id),payload:{published:trader.published,onboarding_status:trader.onboarding_status,verification_status:trader.verification_status,verified:trader.verified,mode:trader.mode,live_execution_authorized:false}});return send(res,200,{trader,live_execution_authorized:false});}
 if(req.method==='GET'&&route==='/api/admin/copy-policies')return send(res,200,{items:await repos.admin.listCopyPolicies(requestUrl(req).searchParams.get('limit')),mode:'SHADOW',live_execution_authorized:false});
 if(req.method==='GET'&&route==='/api/admin/rentals')return send(res,200,{items:(await pool.query(`SELECT rental_id,trader_id,status,monthly_rate_bps,amount_due_usd,currency,period_start,period_end,paid_at,payment_status,payment_reference,created_at,updated_at FROM execution_engine_rentals ORDER BY created_at DESC LIMIT 200`)).rows.map(rentalProjection)});
 if(req.method==='GET'&&route==='/api/admin/billing/ledger')return send(res,200,{items:(await pool.query(`SELECT * FROM billing_ledger ORDER BY created_at DESC LIMIT 200`)).rows});
 if(req.method==='PATCH'&&p[1]==='admin'&&p[2]==='copy-policies'&&p[3]){const body=await jsonBody(req);const updated=await repos.admin.updateCopyPolicy(p[3],body);if(!updated)return send(res,404,{error:'copy_policy_not_found'});await repos.auditEvents.append({event_type:'ADMIN_COPY_MANDATE_UPDATED',actor:'admin',entity_type:'copy_policy',entity_id:String(updated.policy_id),payload:{enabled:updated.enabled,status:updated.status,mode:'SHADOW',live_execution_authorized:false}});return send(res,200,{mandate:updated,mode:'SHADOW',live_execution_authorized:false});}
 if(req.method==='GET'&&route==='/api/admin/fees/history')return send(res,200,{items:(await pool.query(`SELECT version_number,performance_fee_bps,execution_fee_bps,execution_rental_fee_bps,enabled,created_by,mode,live_execution_authorized,created_at FROM platform_fee_config_versions ORDER BY version_number DESC LIMIT 100`)).rows,mode:'SHADOW',live_execution_authorized:false});
 if(req.method==='POST'&&route==='/api/admin/fees/apply-shadow'){if(executionMode!=='SHADOW'||liveEnabled)return send(res,423,{error:'fee_change_shadow_only',mode:executionMode,live_execution_authorized:false});const body=await jsonBody(req);if(body.confirm_shadow_only!==true)throw new Error('fee_change_confirmation_required');const performance=Number(body.performance_fee_bps),execution=Number(body.execution_fee_bps),rental=Number(body.execution_rental_fee_bps);for(const [name,value] of [['performance_fee',performance],['execution_fee',execution],['execution_rental_fee',rental]])if(!Number.isInteger(value)||value<0||value>10000)throw new Error(`invalid_${name}_bps`);if(performance+execution>10000)throw new Error('combined_fee_exceeds_100_percent');if(typeof body.enabled!=='boolean')throw new Error('invalid_fee_enabled');const client=await pool.connect();try{await client.query('BEGIN');const config=(await client.query(`UPDATE platform_fee_config SET performance_fee_bps=$1,execution_fee_bps=$2,execution_rental_fee_bps=$3,enabled=$4,updated_at=now() WHERE config_id=1 RETURNING config_id,performance_fee_bps,execution_fee_bps,execution_rental_fee_bps,currency,enabled,updated_at`,[performance,execution,rental,body.enabled])).rows[0];const version=(await client.query(`INSERT INTO platform_fee_config_versions(performance_fee_bps,execution_fee_bps,execution_rental_fee_bps,enabled,created_by) VALUES($1,$2,$3,$4,$5) RETURNING version_number,performance_fee_bps,execution_fee_bps,execution_rental_fee_bps,enabled,created_by,mode,live_execution_authorized,created_at`,[performance,execution,rental,body.enabled,'admin-control-panel'])).rows[0];await client.query('COMMIT');await repos.auditEvents.append({event_type:'PLATFORM_FEE_CONFIG_VERSION_APPLIED',actor:'admin',entity_type:'platform_fee_config',entity_id:String(version.version_number),payload:{performance_fee_bps:performance,execution_fee_bps:execution,execution_rental_fee_bps:rental,enabled:body.enabled,version_number:version.version_number,mode:'SHADOW',live_execution_authorized:false}});return send(res,200,{config,version,mode:'SHADOW',live_execution_authorized:false,network_submission_authorized:false,signer_required:false});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 if(req.method==='PATCH'&&route==='/api/admin/fees')return send(res,409,{error:'fee_control_lifecycle_required',mode:'SHADOW',live_execution_authorized:false,network_submission_authorized:false,signer_required:false});
 if(req.method==='GET'&&(route==='/'||route==='/dashboard'))return send(res,200,fs.readFileSync(path.resolve(process.cwd(),'web/dashboard.html'),'utf8'),'text/html; charset=utf-8');
 if(req.method==='GET'&&route==='/admin')return send(res,200,fs.readFileSync(path.resolve(process.cwd(),'web/admin.html'),'utf8'),'text/html; charset=utf-8');
 return send(res,404,{error:'not_found',path:route,method:req.method});
 }catch(e){console.error(e);return send(res,errorStatus(e),{error:e.message});}});
async function start(){if(pool)await runMigrations(pool,path.resolve(process.cwd(),'migrations'));memberShadowScheduler=startMemberAutoTradeShadowScheduler({pool,repos,env:process.env});server.listen(PORT,'0.0.0.0',()=>console.log(`Aether API listening on ${PORT}`));}
start().catch(e=>{console.error('startup_failed',e);process.exit(1);});